version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/tekblogg-web'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/tekblogg-cms'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'