name: Deploy web

on:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./tekblogg-web
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./tekblogg-web/.nvmrc
          cache: yarn
          cache-dependency-path: ./tekblogg-web/yarn.lock

      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint && yarn ts-lint

      - name: Build, run and test
        run: yarn build && yarn start-and-test:production

  deploy-production:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
